# Generated by Django 2.2.6 on 2019-10-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Inprocess', 'Inprocess'), ('Done', 'Done')], max_length=100),
        ),
    ]
