# Generated by Django 2.2.6 on 2019-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191012_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
