# Generated by Django 2.2.6 on 2019-10-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191012_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
    ]
